pipeline {
    agent any
    environment {
      MAVEN_HOME = '/apache-maven-3.9.9' // Adjust this to your Maven installation path
      PATH = "$MAVEN_HOME/bin:$PATH"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
